# Курс «Алгоритмы анализа данных»

## Урок 1. Алгоритм линейной регрессии. Градиентный спуск

### Домашняя работа к уроку 5

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [2]:
def calc_mse(y, y_pred):
  err = np.mean((y - y_pred)**2)
  return err

#### Задание 1

Подберите скорость обучения (alpha) и количество итераций.

In [3]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 2, 1, 3, 0, 5, 10, 1, 2]])

In [4]:
y = [45, 55, 50, 59, 65, 35, 75, 80, 50, 60]

In [5]:
n = X.shape[1]
alpha = 1e-3
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.001)

In [6]:
for i in range(7001):
  y_pred = np.dot(W, X)
  err = calc_mse(y, y_pred)
  for ii in range(W.shape[0]):
    W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))
  if i % 1000 == 0:
    print(i, W, err)

0 [1.1102 0.84  ] 3173.15
1000 [31.66648131  6.78503276] 176.46806566379882
2000 [41.73215361  4.92632937] 62.2342399245102
3000 [45.28877016  4.26957292] 47.97214782992787
4000 [46.54546925  4.03751382] 46.191525762883025
5000 [46.98951279  3.95551778] 45.96921511416333
6000 [47.14641166  3.92654521] 45.94145963171206
7000 [47.2018505  3.916308 ] 45.93799435998291


Оптимальное количество итераций $7000$, оптимальное $alpha = 0,001$

#### Задание 2

В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее.

In [42]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 2, 1, 3, 0, 5, 10, 1, 2]])

In [43]:
y = [45, 55, 50, 59, 65, 35, 75, 80, 50, 60]

In [39]:
n = X.shape[1]
alpha = 1e-4
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.0001)

In [30]:
for i in range(1000):
  y_pred = np.dot(W, X)
  err = calc_mse(y, y_pred)
  for ii in range(W.shape[0]):
    W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))
  if i % 100 == 0:
    print(i, W, err)

0 [1.01102 0.534  ] 3173.15
100 [2.02168794 3.452835  ] 2207.6942101483005
200 [2.88306663 5.58962851] 1670.7027004086372
300 [3.63289519 7.14848061] 1368.0832412796256
400 [4.29908617 8.28027926] 1193.7493344933293
500 [4.90228732 9.09657298] 1089.714750358689
600 [5.45777535 9.67982684] 1024.2828984889416
700 [ 5.97685612 10.0910047 ] 980.1260644155933
800 [ 6.46789973 10.37517467] 947.770026039189
900 [ 6.93710574 10.56565326] 922.0330206910179


In [41]:
for i in range(1000):
  y_pred = np.dot(W, X)
  err = calc_mse(y, y_pred)
  '''for ii in range(W.shape[0]):
    W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))'''
  W -= alpha * (1/n * 2 * np.sum(X * (y_pred - y), axis=ii))
  if i % 100 == 0:
    print(i, W, err)

0 [1.01102 0.534  ] 3173.15
100 [2.02168794 3.452835  ] 2207.6942101483005
200 [2.88306663 5.58962851] 1670.7027004086372
300 [3.63289519 7.14848061] 1368.0832412796256
400 [4.29908617 8.28027926] 1193.7493344933293
500 [4.90228732 9.09657298] 1089.714750358689
600 [5.45777535 9.67982684] 1024.2828984889416
700 [ 5.97685612 10.0910047 ] 980.1260644155933
800 [ 6.46789973 10.37517467] 947.770026039189
900 [ 6.93710574 10.56565326] 922.0330206910179


#### Задание 3

Вместо того, чтобы задавать количество итераций, задайте условие остановки алгоритма - когда ошибка за итерацию
начинает изменяться ниже определенного порога (упрощенный аналог параметра tol в линейной регрессии в sklearn).

In [11]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 2, 1, 3, 0, 5, 10, 1, 2]])

In [12]:
y = [45, 55, 50, 59, 65, 35, 75, 80, 50, 60]

In [13]:
n = X.shape[1]
alpha = 1e-2
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.01)

In [14]:
count = 1
epsilon = 0.00000001
err = 1
err_prev = 0
while math.fabs(err_prev - err) > epsilon:
    count += 1
    for i in range(count):
        err_prev = err
        y_pred = np.dot(W, X)
        err = calc_mse(y, y_pred)
        for ii in range(W.shape[0]):
            W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))
        
#         if i % 1000 == 0:
print(count, W, err)

45 [47.23125009  3.91087914] 45.93750043755129
